---

- name: Ensure that directory to store APT repository keys exists.
  become: true
  ansible.builtin.file:
    path: /usr/share/keyrings
    state: directory
    owner: root
    group: root
    mode: 0774

- name: Adding Brave browser keyring
  ansible.builtin.apt_key:
    url: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
    keyring: /usr/share/keyrings/brave-browser-archive-keyring.gpg

- name: Adding Brave browser repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main"
    state: present
    update_cache: true

- name: Installing Brave browser
  ansible.builtin.apt:
    name: brave-browser
    state: latest
    update_cache: true
