---

- name: Ensure that directory to store APT repository keys exists.
  become: true
  ansible.builtin.file:
    path: /usr/share/keyrings
    state: directory
    owner: root
    group: root
    mode: 0774

- name: Adding Brave browser keyring
  ansible.builtin.apt_key:
    url: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
    keyring: /usr/share/keyrings/brave-browser-archive-keyring.gpg

- name: Add Brave repository to list of repositories
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/brave-browser-release.list
    content: |
      deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main
    mode: 0664

- name: Installing Brave browser
  ansible.builtin.apt:
    name: brave-browser
    state: latest
    update_cache: true
