---

- name: Adding Microsoft packages signing key
  ansible.builtin.apt_key:
    url: "https://packages.microsoft.com/keys/microsoft.asc"
    state: present

- name: Adding Microsoft Edge repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://packages.microsoft.com/repos/edge stable main"
    state: present
    update_cache: true

- name: Installing Microsoft Edge browser
  ansible.builtin.apt:
    name: microsoft-edge-stable
    state: latest
    update_cache: true
