---

- name: Ensure that directory to store APT repository keys exists.
  become: true
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    owner: root
    group: root
    mode: 0775

- name: Adding Mozilla keyring
  ansible.builtin.apt_key:
    url: https://packages.mozilla.org/apt/repo-signing-key.gpg
    keyring: /etc/apt/keyrings/packages.mozilla.org.asc

- name: Adding Mozilla Firefox repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/packages.mozilla.org.asc] https://packages.mozilla.org/apt mozilla main"
    state: present
    update_cache: true

- name: Installing Mozilla Firefox browser
  ansible.builtin.apt:
    name: firefox
    state: latest
    update_cache: true
