---

- name: Check if keyring exists
  ansible.builtin.stat:
    path: /etc/apt/keyrings/packages.mozilla.org.asc
  register: keyring_file

- name: Ensure that directory to store APT repository keys exists.
  become: true
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    owner: root
    group: root
    mode: 0775
  when: not keyring_file.stat.exists

- name: Get keyring file
  become: true
  ansible.builtin.get_url:
    url: https://packages.mozilla.org/apt/repo-signing-key.gpg
    dest: /etc/apt/keyrings/packages.mozilla.org.asc
    mode: 0755
  when: not keyring_file.stat.exists

- name: Add the Mozilla APT repository to your sources list
  ansible.builtin.command:
    cmd: echo "deb [signed-by=/etc/apt/keyrings/packages.mozilla.org.asc] https://packages.mozilla.org/apt mozilla main" | sudo tee -a /etc/apt/sources.list.d/mozilla.list > /dev/null
  when: not keyring_file.stat.exists

- name: Install Firefox
  become: true
  ansible.builtin.apt:
    update_cache: true
    name: firefox
    state: latest
