---

- name: Check if keyring exists
  ansible.builtin.stat:
    path: /usr/share/keyrings/brave-browser-archive-keyring.gpg
  register: keyring_file

- name: Get keyring file
  ansible.builtin.get_url:
    url: https://packages.mozilla.org/apt/repo-signing-key.gpg
    dest: "/etc/apt/keyrings/packages.mozilla.org.asc"
    mode: "0755"
  when: not keyring_file.stat.exists
  become: true

- name: Add Brave repository to list of repositories
  become: true
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/mozilla.list
    content: |
      echo "deb [signed-by=/etc/apt/keyrings/packages.mozilla.org.asc] https://packages.mozilla.org/apt mozilla main"
    mode: "0755"

- name: Install Firefox
  ansible.builtin.apt:
    name: firefox
    state: latest
    update_cache: true
  become: true
