---

# tasks to complete before running roles
- hosts: all
  tags: always
  become: true
  pre_tasks:
    - name: pre-run | update package cache and upgrade all packages
      tags: always
      ansible.builtin.apt: 
        update_cache: yes 
        upgrade: safe
      changed_when: false

# run roles
- hosts: all
  tags: base
  become: true
  roles: 
     - base

- hosts: server
  tags: server
  become: true
  roles: 
     - server

- hosts: workstation
  tags: workstation
  become: true
  roles: 
     - workstation
     
# end of run cleanup
- hosts: all
  tags: always
  become: true
  tasks:
  - name: cleanup package cache (debian)
    tags: always
    ansible.builtin.apt:
      autoclean: yes
    changed_when: false

  - name: autoremove orphan packages (debian)
    tags: always
    ansible.builtin.apt:
      autoremove: yes
      purge: yes
