---

- name: Add APT signing key to a specific keyring file
  ansible.builtin.get_url:
    url: https://syncthing.net/release-key.gpg
    dest: /etc/apt/keyrings/syncthing-archive-keyring.gpg

- name: Add syncthing channel to APT sources list of repositories
  become: true
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/syncthing.list
    content: |
      "deb [signed-by=/etc/apt/keyrings/syncthing-archive-keyring.gpg] https://apt.syncthing.net/ syncthing stable"

- name: Install Syncthing
  become: true
  ansible.builtin.apt:
    name: syncthing
    state: latest
    update_cache: true
