---

- name: Check if keyring exists
  ansible.builtin.stat:
    path: /etc/apt/keyrings/syncthing-archive-keyring.gpg
  register: keyring_file

- name: Get keyring file
  become: true
  ansible.builtin.get_url:
    url: https://syncthing.net/release-key.gpg
    dest: /etc/apt/keyrings/syncthing-archive-keyring.gpg
    mode: 0644
  when: not keyring_file.stat.exists

- name: Add Syncthing stable channel repository to list of repositories
  become: true
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/syncthing.list
    content: |
      deb [signed-by=/etc/apt/keyrings/syncthing-archive-keyring.gpg] https://apt.syncthing.net/ syncthing stable
    mode: 0644

- name: Install Syncthing
  become: true
  ansible.builtin.apt:
    name: syncthing
    state: latest
    update_cache: true
