---

- name: somerepo | no apt key
  ansible.builtin.get_url:
    url: https://syncthing.net/release-key.gpg
    dest: /etc/apt/keyrings/syncthing-archive-keyring.gpg

- name: somerepo | apt source
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/syncthing-archive-keyring.gpg] https://apt.syncthing.net/ syncthing stable"
    state: present
    
- name: Install Syncthing
  become: true
  ansible.builtin.apt:
    name: syncthing
    state: latest
    update_cache: true
