- name: Check if 1st run
  ansible.builtin.stat:
    path: /home/temhr/containers/steamos/first
  register: init_file

# set up steamos support
- name: mk directory for steamos
  ansible.builtin.file:
    path: /home/temhr/{{ item.dir }}
    state: directory
    owner: temhr
    group: root
  with_items:
    - { dir: containers/steamos }
  when: not init_file.stat.exists
  
- name: steamos setup
  ansible.builtin.command: distrobox create --home /home/temhr/containers/steamos --name steamos --image ghcr.io/linuxserver/steamos:latest --hostname steamos --nvidia
  become: yes
  become_user: temhr
  when: not init_file.stat.exists
