- name: verify if this is initial run
  ansible.builtin.stat:
    path: /home/temhr/containers/steamos/first
  register: init_file

# set up steamos support
- name: mk directory for steamos
  ansible.builtin.file:
    path: /home/temhr/containers/steamos
    state: directory
    owner: temhr
    group: root
    mode: 0770
  when: not init_file.stat.exists
  
- name: steamos setup
  ansible.builtin.command: distrobox-create --home /home/temhr/containers/steamos --name steamos --image ghcr.io/linuxserver/steamos:latest --nvidia --yes
  become_user: temhr
  when: not init_file.stat.exists

- name: steamos setup | creating initial run flag
  tags: steamos
  ansible.builtin.file:
    path: /home/temhr/containers/steamos/first
    owner: temhr
    state: touch
  when: not init_file.stat.exists
