---
# tasks to complete before running roles
- hosts: all or localhost
  tags: always
  become: true

  tasks:
  - name: Installs new packages to resolve new dependencies, but never removes packages
    ansible.builtin.apt:
      update_cache: true
      upgrade: safe
    changed_when: false

  - name: Remove useless packages from the cache
    ansible.builtin.apt:
      autoclean: true
    changed_when: false

  - name: Remove dependencies that are no longer required and purge their configuration files
    ansible.builtin.apt:
      autoremove: yes
      purge: true
    changed_when: false
