- name: users | temhr | remove preinstalled clutter from home directory
  ansible.builtin.file:
    path: /home/temhr/{{ item }}
    state: absent
  with_items:
    - Public
    - Templates

- name: users | temhr | create personal config directories
  tags: dotfiles,dotfiles-temhr
  ansible.builtin.file:
    path: /home/temhr/{{ item.dir }}
    state: directory
    owner: temhr
    group: root
    mode: 0760
  with_items:
    - { dir: .config }
    - { dir: .config/autostart }
    - { dir: .local }
    - { dir: .local/share }
    - { dir: .local/share/applications }
    - { dir: bin }
    - { dir: projects }
