- block:

  # set up home folder
  - import_tasks: users/home_temhr.yml
  
  # install software
  - import_tasks: software/packages_cleanup.yml
  - import_tasks: software/packages_distro.yml
  - import_tasks: software/packages_utilities.yml
  
  # install repository & software
  - import_tasks: repositories/brave_browser.yml
  
  # set up flatpak environment
  - import_tasks: flatpak_setup.yml
  
  # install flatpaks
  - import_tasks: flatpak/discord.yml

  rescue:
    - set_fact: task_failed=true
