- block:

  # install software
  - import_tasks: software/packages_cleanup.yml
  - import_tasks: software/packages_distro.yml
  - import_tasks: software/packages_utilities.yml

  rescue:
    - set_fact: task_failed=true
