- block:

  # setup home folder
  - ansible.builtin.import_tasks: users/home_temhr.yml
  
  # install software
  - ansible.builtin.import_tasks: software/packages_cleanup.yml
  - ansible.builtin.import_tasks: software/packages_distro.yml
  - ansible.builtin.import_tasks: software/packages_utilities.yml
  
  # install repository & software
  - ansible.builtin.import_tasks: repositories/brave_browser.yml
  
  # setup software environments
  - ansible.builtin.import_tasks: setup_distrobox.yml
  - ansible.builtin.import_tasks: setup_flatpak.yml
  
  # setup nfs share
  - ansible.builtin.import_tasks: setup_autofs.yml

  # install distrobox containers
  - ansible.builtin.import_tasks: distrobox/steamos.yml
  #- ansible.builtin.import_tasks: distrobox/ubox.yml
  
  # install flatpaks
  - ansible.builtin.import_tasks: flatpak/discord.yml

  rescue:
    - set_fact: task_failed=true
