- block:

  # set up flatpak environment
  - import_tasks: flatpak_setup.yml
  
  # install software
  - import_tasks: software/packages_cleanup.yml
  - import_tasks: software/packages_distro.yml
  - import_tasks: software/packages_utilities.yml
  
  # install flatpaks
  - import_tasks: flatpak/brave_browser.yml

  rescue:
    - set_fact: task_failed=true
