# setup distrobox
- name: distrobox | copy distrobox-assemble file
  tags: distrobox,copy,temhr,steam
  ansible.builtin.copy:
    src: files/distrobox_steamos.ini
    dest: /home/temhr/distrobox_steamos.ini
    owner: temhr
    group: root
    mode: 0770

- name: Ensure podman/distrobox is installed.
  become: true
  ansible.builtin.package:
    state: latest
    name:
      - podman
      - distrobox

- name: Create a distrobox container
  become: false
  become_user: temhr
  ansible.builtin.command: 
    cmd: distrobox-assemble create --file https://raw.githubusercontent.com/Temhr/Ansi/refs/heads/main/roles/workstation/files/distrobox_ubuntu.ini
