# setup distrobox support
- name: mk directories for distrobox containers
  ansible.builtin.file:
    path: /home/temhr/{{ item.dir }}
    state: directory
    owner: temhr
    group: root
  with_items:
    - { dir: containers }

# setup distrobox support
- name: mk temp directories for ansible
  ansible.builtin.file:
    path: /tmp/temhr/.ansible/tmp
    state: directory
    owner: temhr
    group: root
    mode: 760
