- name: system setup | autofs | install package
  tags: autofs
  ansible.builtin.package:
    state: latest
    name:
      - autofs

- name: system setup | autofs | start and enable daemon
  tags: autofs
  ansible.builtin.service:
    name: autofs
    state: started
    enabled: true

- name: system setup | autofs | Check if 1st run
  ansible.builtin.stat:
    path: /etc/auto.nfs
  register: auto_file

- name: system setup | autofs | save auto.master file
  tags: nfs
  ansible.builtin.command: mv /etc/auto.master /etc/auto.master.orig
  become: yes
  when: not auto_file.stat.exists

- name: system setup | autofs | copy auto.master config file
  tags: autofs,dotfiles,dotfiles-jay
  ansible.builtin.copy:
    src: files/nfs_auto.master
    dest: /etc/auto.master
    owner: root
    group: root
    mode: 0644
  when: not auto_file.stat.exists

- name: system setup | autofs | copy auto.nfs config file
  tags: autofs,dotfiles,dotfiles-jay
  ansible.builtin.copy:
    src: files/nfs_auto.nfs
    dest: /etc/auto.nfs
    owner: root
    group: root
    mode: 0644
  when: not auto_file.stat.exists
