# setup distrobox support
- name: mk directories for distrobox containers
  ansible.builtin.file:
    path: /home/temhr/containers
    state: directory
    owner: temhr
    group: root
    mode: 0770

- name: Ensure podman/distrobox is installed.
  become: true
  become_user: temhr
  ansible.builtin.package:
    state: latest
    name:
      - podman
      - distrobox
