# setup distrobox support
- name: mk directories for distrobox containers
  ansible.builtin.file:
    path: /home/temhr/containers
    state: directory
    owner: temhr
    group: root

# setup distrobox support
- name: mk temp directories for ansible
  ansible.builtin.file:
    path: /tmp/temhr/.ansible/tmp
    state: directory
    owner: temhr
    group: root
    mode: 760
