# set up flatpak support
- name: mk directories for steam
  ansible.builtin.file:
    path: /home/temhr/{{ item.dir }}
    state: directory
    owner: temhr
    group: temhr
  with_items:
    - { dir: containers }
    - { dir: containers/steamos }

- name: steamos setup
  ansible.builtin.command: distrobox create --home /home/temhr/containers/steamos --name steamos --image ghcr.io/linuxserver/steamos:latest --hostname steamos --nvidia
  become: yes
  become_user: temhr
