# setup distrobox
- name: distrobox | copy distrobox-assemble file
  tags: distrobox,copy,temhr,steam
  ansible.builtin.copy:
    src: files/distrobox_steamos
    dest: /home/temhr/distrobox_steamos.init
    owner: temhr
    group: root
    mode: 0770

- name: Ensure podman/distrobox is installed.
  become: true
  ansible.builtin.package:
    state: latest
    name:
      - podman
      - distrobox
