---

- name: users | ansibot | create ansibot user
  tags: always
  ansible.builtin.user:
    name: ansibot
    group: root
    state: present
    
- name: users | ansibot | add sudoers file
  tags: settings,ansibot,sudo,system,users
  ansible.builtin.copy:
    src: files/users/sudoers_ansibot
    dest: /etc/sudoers.d/ansibot
    owner: root
    group: root
    mode: 0440

- name: users | ansibot | Home directory
  tags: ansibot,users
  ansible.builtin.file:
    path: /home/ansibot
    state: directory
    owner: ansibot
    group: root
    mode: 0770
