---

- name: users | ansibot | create ansibot user
  tags: always
  ansible.builtin.user:
    name: ansibot
    groups: root
    
- name: users | ansibot | add sudoers file
  tags: settings,ansibot,sudo,system,users
  copy:
    src: files/users/sudoers_ansibot
    dest: /etc/sudoers.d/ansibot
    owner: root
    group: root
    mode: 0440
