---

- name: users | ansibot | create ansibot user
  user:
    name: ansibot
    system: yes
    
- name: users | ansibot | create ansibot group
  tags: groups,ansibot,users
  group:
    name: ansibot
    state: present
    
- name: users | ansibot | add sudoers file
  tags: settings,ansibot,sudo,system,users
  copy:
    src: files/users/sudoers_ansibot
    dest: /etc/sudoers.d/ansibot
    owner: root
    group: root
    mode: 0440
