- name: users | root | copy dotfiles
  copy:
    src: users/root/{{ item.src }}
    dest: /root/{{ item.dest}}
    owner: root
    group: root
    mode: 0600
  with_items:
      - { src: 'bash/bashrc', dest: '.bashrc' }
      - { src: 'bash/bash_profile', dest: '.bash_profile' }
      - { src: 'bash/profile', dest: '.profile' }
  tags: dotfiles
