- name: users | temhr | create group
  tags: groups,temhr,users
  group:
    name: temhr
    state: present

- name: users | temhr | temhr | add sudoers file
  tags: temhr,settings,ansibot,sudo,system,users
  copy:
    src: files/users/sudoers_temhr
    dest: /etc/sudoers.d/temhr
    owner: root
    group: root
    mode: 0440

- name: users | temhr | create config directories
  tags: dotfiles,temhr,users,vim
  file:
    path: /home/temhr/{{ item.dir }}
    state: directory
    owner: temhr
    group: temhr
    mode: 0700
  with_items:
    - { dir: '.bash' }
    - { dir: '.config' }
    - { dir: '.config/htop' }
    - { dir: '.config/mc' }

- name: users | temhr | copy dotfiles
  tags: dotfiles,users,temhr,users
  copy:
    src: files/users/temhr/{{ item.src }}
    dest: /home/temhr/{{ item.dest }}
    owner: temhr
    group: temhr
    mode: 0600
  with_items:
    - { src: 'bash/bash_aliases', dest: '.bash/bash_aliases' }
    - { src: 'bash/bash_profile', dest: '.bash_profile' }
    - { src: 'bash/bash_prompt', dest: '.bash/bash_prompt' }
    - { src: 'bash/bash_functions', dest: '.bash/bash_functions' }
    - { src: 'bash/bashrc', dest: '.bashrc' }
    - { src: 'bash/profile', dest: '.profile' }
    - { src: 'htop/htoprc', dest: '.config/htop/htoprc' }
    - { src: 'inputrc', dest: '.inputrc' }
    - { src: 'mc/mc.ini', dest: '.config/mc/ini' }
