- name: users | temhr | create temhr user
  tags: always
  ansible.builtin.user:
    name: temhr
    group: root
    state: present

- name: users | temhr | Home directory
  tags: temhr,users
  ansible.builtin.file:
    path: /home/temhr
    state: directory
    owner: temhr
    group: root
    mode: 0770

- name: users | temhr | temhr | add sudoers file
  tags: temhr,settings,ansibot,sudo,system,users
  ansible.builtin.copy:
    src: files/users/sudoers_temhr
    dest: /etc/sudoers.d/temhr
    owner: root
    group: root
    mode: 0440

- name: users | temhr | create config directories
  tags: dotfiles,temhr,users,vim
  ansible.builtin.file:
    path: /home/temhr/{{ item.dir }}
    state: directory
    owner: temhr
    group: root
    mode: 0770
  with_items:
    - { dir: '.bash' }
    - { dir: '.config' }
    - { dir: '.config/htop' }
    - { dir: '.config/mc' }

- name: users | temhr | copy dotfiles
  tags: dotfiles,users,temhr,users
  ansible.builtin.copy:
    src: files/users/temhr/{{ item.src }}
    dest: /home/temhr/{{ item.dest }}
    owner: temhr
    group: root
    mode: 0660
  with_items:
    - { src: 'inputrc', dest: '.inputrc' }
    - { src: 'bash/bash_aliases', dest: '.bash/bash_aliases' }
    - { src: 'bash/bash_profile', dest: '.bash_profile' }
    - { src: 'bash/bash_prompt', dest: '.bash/bash_prompt' }
    - { src: 'bash/bash_functions', dest: '.bash/bash_functions' }
    - { src: 'bash/profile', dest: '.profile' }
    - { src: 'htop/htoprc', dest: '.config/htop/htoprc' }
    - { src: 'mc/mc.ini', dest: '.config/mc/ini' }

- name: users | temhr | copy dotfiles (Debian)
  tags: dotfiles,users,temhr,users
  ansible.builtin.copy:
    src: files/users/temhr/{{ item.src }}
    dest: /home/temhr/{{ item.dest }}
    owner: temhr
    group: root
    mode: 0660
  with_items:
    - { src: 'bash/bashrc-deb', dest: '.bashrc' }
  when: ansible_distribution == "Debian"
  
- name: users | temhr | copy dotfiles (siduction)
  tags: dotfiles,users,temhr,users
  ansible.builtin.copy:
    src: files/users/temhr/{{ item.src }}
    dest: /home/temhr/{{ item.dest }}
    owner: temhr
    group: root
    mode: 0660
  with_items:
    - { src: 'bash/bashrc-sid', dest: '.bashrc' }
  when: ansible_distribution == "siduction"
