- name: users | ansibot | add sudoers file
  tags: settings,ansibot,sudo,system,users
  copy:
    src: users/sudoers_ansibot
    dest: /etc/sudoers.d/ansibot
    owner: root
    group: root
    mode: 0440
