- block:

  # install software
  - import_tasks: software/packages_utilities.yml
  
  # install repository & software
  - import_tasks: repositories/syncthing.yml
  
  # install repository & software
  - import_tasks: setup_nfsserver.yml

  rescue:
    - set_fact: task_failed=true
