- name: Check if 1st run
  ansible.builtin.stat:
    path: /etc/exports.orig
  register: nfsexports_file

- name: nfs server | save exports file
  tags: nfs
  ansible.builtin.command: mv /etc/exports /etc/exports.orig
  become: yes
  when: not nfsexports_file.stat.exists

- name: nfs server | add new exports file
  tags: nfs
  ansible.builtin.copy:
    src: files/nfs_exports
    dest: /etc/exports
    owner: root
    group: root
    mode: 0644
  when: not nfsexports_file.stat.exists
