- name: system setup | package cleanup | remove unneeded packages (debian)
  tags: cleanup,packages,system,settings
  package:
    state: absent
    name:
      - cowsay
  when: ansible_distribution in ["Debian"]
