- name: system setup | utilities | install utility packages
  tags: packages,system,settings
  ansible.builtin.package:
    state: latest
    name:
      - adb
      - at
      - autofs
      - busybox
      - colordiff
      - cron
      - curl
      - ethtool
      - gcc
      - git
      - htop
      - iperf
      - iotop
      - lsof
      - mc
      - mosh
      - nala
      - ncdu
      - neofetch
      - net-tools
      - nfs-kernel-server
      - nmap
      - ranger
      - rsync
      - screen
      - sshfs
      - sudo
      - tmux
      - traceroute
      - usbutils
      - vim-nox
      - wget
      - whois
