- name: ansible setup | ensure ansible is the latest version
  tags: ansible,ansible-setup
  ansible.builtin.package:
    name: ansible
    state: latest

- name: ansible setup | create ansible log file
  tags: ansible,ansible-setup
  ansible.builtin.file:
    path: /var/log/ansible.log
    owner: ansibot
    group: root
    mode: 0664
    state: touch
  changed_when: False

- name: ansible setup | add logrotate config for ansible log file
  tags: ansible-setup
  ansible.builtin.copy:
    src: files/ansible_setup/logrotate
    dest: /etc/logrotate.d/ansible
    owner: root
    group: root
    mode: 0644

- name: ansible setup | add thrice daily ansible cronjob playbook
  tags: ansible-setup
  ansible.builtin.copy:
    src: files/ansible_setup/thrice_daily_ansi.yml
    dest: /usr/local/bin/thrice_daily_ansi.yml
    owner: root
    group: root
    mode: 0755

- name: ansible setup | remove default ansible directory (/etc/ansible) from host
  tags: ansible,ansible-setup
  ansible.builtin.file:
    path: /etc/ansible
    state: absent

- name: ansible setup | generate provision script from template
  tags: ansible,ansible-setup,scripts
  template:
    src: templates/provision.sh.j2
    dest: /usr/local/bin/provision
    owner: root
    group: root
    mode: 0755
