- block:
  # Make sure users exist on the system
  - import_tasks: users/temhr.yml
  - import_tasks: users/root.yml
  - import_tasks: users/ansibot.yml

  # Set up the ansible environment
  - import_tasks: setup_ansible.yml

  # install software
  - import_tasks: software/packages_cleanup.yml
  - import_tasks: software/packages_utilities.yml

  # Perform remaining tasks:
  - import_tasks: system_setup/clock.yml
  - import_tasks: system_setup/cron.yml
  - import_tasks: system_setup/logging.yml

  rescue:
    - set_fact: task_failed=true
