---

- name: system setup | cron | Check if AnsiLog.txt exists
  ansible.builtin.stat:
    path: /home/temhr/AnsiLog.txt
  register: ansilog_file

- name: system setup | cron | Touch AnsiLog.txt
  tags: cron
  ansible.builtin.file:
    path: /home/temhr/AnsiLog.txt
    owner: ansibot
    group: root
    mode: 0664
    state: touch
  when: not ansilog_file.stat.exists

- name: system setup | cron | Ansible autopull setup
  tags: cron
  ansible.builtin.cron:
    name: "ansible provision"
    user: ansibot
    minute: "*/17"
    job: "/usr/bin/ansible-pull -o -U https://github.com/Temhr/Ansi.git >> /home/temhr/AnsiLog.txt"

- name: system setup | cron | Check if Ansi.txt exists
  ansible.builtin.stat:
    path: /home/temhr/Ansi.txt
  register: ansi_file

- name: system setup | cron | Touch Ansi.txt
  tags: cron
  ansible.builtin.file:
    path: /home/temhr/Ansi.txt
    owner: ansibot
    group: root
    mode: 0664
    state: touch
  when: not ansi_file.stat.exists

- name: system setup | cron | Quarter-daily nala update / apt upgrade
  tags: cron
  ansible.builtin.cron:
    name: "ansible quarter daily"
    user: ansibot
    hour: "*/6"
    minute: 0
    job: "date >> /home/temhr/Ansi.txt && sudo nala update >> /home/temhr/Ansi.txt && sudo apt upgrade -y >> /home/temhr/Ansi.txt && sudo apt autoremove -y >> /home/temhr/Ansi.txt"

- name: system setup | cron | Weekly Tuesday log deletes
  tags: cron
  ansible.builtin.cron:
    name: "ansible weekly delete"
    user: ansibot
    weekday: 2
    hour: 0
    minute: 0
    job: "rm /home/temhr/Ansi.txt /home/temhr/AnsiLog.txt"

- name: system setup | cron | start service on boot
  tags: cron,systemd_service,boot
  ansible.builtin.systemd_service:
    name: cron
    enabled: True
    state: started

- name: system setup | cron | schedule ansible cleanup at boot
  tags: cron
  ansible.builtin.cron:
    name: "ansible refresh at boot"
    user: ansibot
    special_time: reboot
    job: "/bin/rm -rf /home/ansibot/.ansible"
