---

- name: system setup | cron | Check if ansible-pull logfile exists
  ansible.builtin.stat:
    path: /tmp/AnsiLog.txt
  register: ansilog_file

- name: system setup | cron | auto ansible-pull logfile
  tags: cron
  ansible.builtin.file:
    path: /tmp/AnsiLog.txt
    owner: ansibot
    group: root
    mode: 0664
    state: touch
  when: not ansilog_file.stat.exists

- name: system setup | cron | auto ansible-pull setup
  tags: cron
  ansible.builtin.cron:
    name: "ansible provision"
    user: ansibot
    minute: */17
    job: "/usr/bin/ansible-pull -o -U https://github.com/Temhr/Ansi.git >> /tmp/AnsiLog.txt"

- name: system setup | cron | Check if quarter daily logfile exists
  ansible.builtin.stat:
    path: /tmp/Ansi.txt
  register: ansi_file

- name: system setup | cron | auto ansible-pull log file
  tags: cron
  ansible.builtin.file:
    path: /tmp/Ansi.txt
    owner: ansibot
    group: root
    mode: 0664
    state: touch
  when: not ansi_file.stat.exists

- name: system setup | cron | quarter daily update/upgrade
  tags: cron
  ansible.builtin.cron:
    name: "ansible quarter daily"
    user: ansibot
    hour: */6
    minute: 0
    job: "ansible-playbook /usr/local/bin/quarter_daily_ansi.yml >> /tmp/Ansi.txt"

- name: system setup | cron | weekly delete
  tags: cron
  ansible.builtin.cron:
    name: "ansible weekly delete"
    user: ansibot
    weekday: 2
    hour: 0
    minute: 0
    job: "rm /tmp/Ansi.txt /tmp/AnsiLog.txt"

- name: system setup | cron | start service on boot
  tags: cron,systemd_service,boot
  ansible.builtin.systemd_service:
    name: cron
    enabled: True
    state: started

- name: system setup | cron | schedule ansible cleanup at boot
  tags: cron
  ansible.builtin.cron:
    name: "ansible refresh at boot"
    user: ansibot
    special_time: reboot
    job: "/bin/rm -rf /home/ansibot/.ansible"
