---

- name: system setup | cron | auto ansible-pull setup
  tags: cron
  ansible.builtin.cron:
    name: "ansible provision"
    user: ansibot
    minute: "*/5"
    job: "sudo -iH -u ansibot ansible-pull -o -U https://github.com/Temhr/Ansi.git > /var/tmp/AnsiLog.txt"

#- name: system setup | cron | schedule automatic ansible provisioning
#  tags: cron
#  ansible.builtin.cron:
#    name: "ansible provision"
#    user: ansibot
#    hour: "{{ ansible_cron_hour | default('*') }}"
#    minute: "{{ ansible_cron_minute | default('*/5') }}"
#    job: "/usr/local/bin/provision > /home/AnsiLog.txt"

- name: system setup | cron | start service on boot
  ansible.builtin.systemd_service:
    name: cron
    enabled: True
    state: started

- name: system setup | cron | schedule ansible cleanup at boot
  tags: cron
  ansible.builtin.cron:
    name: "ansible refresh at boot"
    user: ansibot
    special_time: reboot
    job: "/bin/rm -rf /home/ansibot/.ansible"
