---

- name: system setup | cron | install cron job (ansible-pull)
  tags: cron
  ansible.builtin.cron:
    user: ansibot
    name: "ansible provision"
    minute: "*/10"
    job: "/usr/bin/ansible-pull -o -U https://github.com/Temhr/Ansi.git > /dev/null"

- name: system setup | cron | schedule ansible cleanup at boot
  tags: cron
  ansible.builtin.cron:
    name: "ansible refresh at boot"
    user: ansibot
    special_time: reboot
    job: "/bin/rm -rf /home/ansibot/.ansible"
